version: "3"
services:
    nginx:
        container_name: ghtk_nginx
        depends_on:
            - php
            - dockerhost
            - redis.ghtk.vn
        image: nginx:alpine
        restart: always
        volumes:
            - ${CASH}
            - ${ECOM}
            - ${ASSET}
            - ${NGINX}
            - ${INVOICE}
            - ./tmp/:/tmp/
        ports:
            - 80:80
    php:
        container_name: ghtk_php
        build: ./php
        restart: always
        env_file:
            - ./database/db.env
        volumes:
            - ${CASH}
            - ${ECOM}
            - ${ASSET}
            - ${XDEBUG}
            - ${INVOICE}
            - ${GEARMAN}
            - ./php/ecom.conf.ini:/usr/local/etc/php/conf.d/ecom.conf.ini
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        expose:
            - 9000
    redis.ghtk.vn:
        container_name: redis.ghtk.vn
        image: redis:alpine
        restart: always
        expose:
            - 6379
        command: redis-server --appendonly yes
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181

    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: "test:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    dockerhost:
        container_name: ghtk_host
        image: qoomon/docker-host
        cap_add: ["NET_ADMIN", "NET_RAW"]
        restart: always
