version: "3"
services:
    nginx:
        container_name: ghtk_nginx
        depends_on:
            - php
            - dockerhost
            - redis.ghtk.vn
        image: nginx:alpine
        restart: always
        volumes:
            - ${CASH}
            - ${ECOM}
            - ${ASSET}
            - ${NGINX}
            - ${INVOICE}
            - ${ERP}
            - ./tmp/:/tmp/
        ports:
            - 80:80
    php:
        container_name: ghtk_php
        build: ./php
        restart: always
        env_file:
            - ./database/db.env
        volumes:
            - ${CASH}
            - ${ECOM}
            - ${ASSET}
            - ${XDEBUG}
            - ${INVOICE}
            - ${ERP}
            - ${GEARMAN}
            - ./php/ecom.conf.ini:/usr/local/etc/php/conf.d/ecom.conf.ini
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        expose:
            - 9000
    redis.ghtk.vn:
        container_name: redis.ghtk.vn
        image: redis:alpine
        restart: always
        expose:
            - 6379
        command: redis-server --appendonly yes
    dockerhost:
        container_name: ghtk_host
        image: qoomon/docker-host
        cap_add: ["NET_ADMIN", "NET_RAW"]
        restart: always
